### ISSUE TITLE
Method View::setScript does not exist

### ISSUE THREAD

**Issue by rafaoski** [wireframe-framework/wireframe-boilerplate#2]
For starters, thanks to teppo for this great structure and work on this project ... 
I noticed a small problem when accessing data.json from the home page ... It seems that the View::setScript() method does not exist ...

![Screenshot](https://user-images.githubusercontent.com/12895367/60773195-5b94dd80-a102-11e9-91cc-aa540b6e4296.png)

**Comment by teppokoivula** [comment]
Sorry @rafaoski – that was an oversight from my part. Method View::setScript() was renamed to View::setView() a while ago, but looks like I forgot to update this reference.

The issue is now fixed with the latest version of the site profile. You can fix it in your local setup by making the following change:

```
-            $this->view->setLayout(null)->setScript('json');
+            $this->view->setLayout(null)->setView('json');
```

Thanks for reporting this!

**Comment by rafaoski** [comment]
Thanks @teppokoivula for the quick fix, now it works great ...
